# Name of your application. Used to uniquely configure containers.
service: my-app

# Name of the container image.
image: layoric/kamalblazor

# Deploy to these servers.
servers:
  web:
    - 78.47.35.45

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
proxy: 
  ssl: true
  host: kamal.reidodon.net
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 8080

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: layoric

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
